# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
excerpt_separator: <!--more-->

# Setup
title:               Fylux
tagline:             'Things'
description:         'Algorithms, Maths, and all.'
url:                 'https://azam-aminuddin.github.io'
baseurl:             'https://azam-aminuddin.github.io'
paginate:            5

# About/contact
author:
  name:              Alfonso L. Casta√±o
  url:               https://github.com/fylux/
  email:             alfonso.cama@hotmail.com

# Custom vars
version:             1.0.0
